"""Centralized constants for uptrend dashboard."""

SECTORS = [
    "sec_basicmaterials",
    "sec_communicationservices",
    "sec_consumercyclical",
    "sec_consumerdefensive",
    "sec_energy",
    "sec_financial",
    "sec_healthcare",
    "sec_industrials",
    "sec_realestate",
    "sec_technology",
    "sec_utilities",
]

INDUSTRIES = [
    "ind_advertisingagencies",
    "ind_aerospacedefense",
    "ind_agriculturalinputs",
    "ind_airlines",
    "ind_airportsairservices",
    "ind_aluminum",
    "ind_apparelmanufacturing",
    "ind_apparelretail",
    "ind_assetmanagement",
    "ind_automanufacturers",
    "ind_autoparts",
    "ind_autotruckdealerships",
    "ind_banksdiversified",
    "ind_banksregional",
    "ind_beveragesbrewers",
    "ind_beveragesnonalcoholic",
    "ind_beverageswineriesdistilleries",
    "ind_biotechnology",
    "ind_broadcasting",
    "ind_buildingmaterials",
    "ind_buildingproductsequipment",
    "ind_businessequipmentsupplies",
    "ind_capitalmarkets",
    "ind_chemicals",
    "ind_closedendfunddebt",
    "ind_closedendfundequity",
    "ind_closedendfundforeign",
    "ind_cokingcoal",
    "ind_communicationequipment",
    "ind_computerhardware",
    "ind_confectioners",
    "ind_conglomerates",
    "ind_consultingservices",
    "ind_consumerelectronics",
    "ind_copper",
    "ind_creditservices",
    "ind_departmentstores",
    "ind_diagnosticsresearch",
    "ind_discountstores",
    "ind_drugmanufacturersgeneral",
    "ind_drugmanufacturersspecialtygeneric",
    "ind_educationtrainingservices",
    "ind_electricalequipmentparts",
    "ind_electroniccomponents",
    "ind_electronicgamingmultimedia",
    "ind_electronicscomputerdistribution",
    "ind_engineeringconstruction",
    "ind_entertainment",
    "ind_exchangetradedfund",
    "ind_farmheavyconstructionmachinery",
    "ind_farmproducts",
    "ind_financialconglomerates",
    "ind_financialdatastockexchanges",
    "ind_fooddistribution",
    "ind_footwearaccessories",
    "ind_furnishingsfixturesappliances",
    "ind_gambling",
    "ind_gold",
    "ind_grocerystores",
    "ind_healthcareplans",
    "ind_healthinformationservices",
    "ind_homeimprovementretail",
    "ind_householdpersonalproducts",
    "ind_industrialdistribution",
    "ind_informationtechnologyservices",
    "ind_infrastructureoperations",
    "ind_insurancebrokers",
    "ind_insurancediversified",
    "ind_insurancelife",
    "ind_insurancepropertycasualty",
    "ind_insurancereinsurance",
    "ind_insurancespecialty",
    "ind_integratedfreightlogistics",
    "ind_internetcontentinformation",
    "ind_internetretail",
    "ind_leisure",
    "ind_lodging",
    "ind_lumberwoodproduction",
    "ind_luxurygoods",
    "ind_marineshipping",
    "ind_medicalcarefacilities",
    "ind_medicaldevices",
    "ind_medicaldistribution",
    "ind_medicalinstrumentssupplies",
    "ind_metalfabrication",
    "ind_mortgagefinance",
    "ind_oilgasdrilling",
    "ind_oilgasep",
    "ind_oilgasequipmentservices",
    "ind_oilgasintegrated",
    "ind_oilgasmidstream",
    "ind_oilgasrefiningmarketing",
    "ind_otherindustrialmetalsmining",
    "ind_otherpreciousmetalsmining",
    "ind_packagedfoods",
    "ind_packagingcontainers",
    "ind_paperpaperproducts",
    "ind_personalservices",
    "ind_pharmaceuticalretailers",
    "ind_pollutiontreatmentcontrols",
    "ind_publishing",
    "ind_railroads",
    "ind_realestatedevelopment",
    "ind_realestatediversified",
    "ind_realestateservices",
    "ind_recreationalvehicles",
    "ind_reitdiversified",
    "ind_reithealthcarefacilities",
    "ind_reithotelmotel",
    "ind_reitindustrial",
    "ind_reitmortgage",
    "ind_reitoffice",
    "ind_reitresidential",
    "ind_reitretail",
    "ind_reitspecialty",
    "ind_rentalleasingservices",
    "ind_residentialconstruction",
    "ind_resortscasinos",
    "ind_restaurants",
    "ind_scientifictechnicalinstruments",
    "ind_securityprotectionservices",
    "ind_semiconductorequipmentmaterials",
    "ind_semiconductors",
    "ind_shellcompanies",
    "ind_silver",
    "ind_softwareapplication",
    "ind_softwareinfrastructure",
    "ind_solar",
    "ind_specialtybusinessservices",
    "ind_specialtychemicals",
    "ind_specialtyindustrialmachinery",
    "ind_specialtyretail",
    "ind_staffingemploymentservices",
    "ind_steel",
    "ind_telecomservices",
    "ind_textilemanufacturing",
    "ind_thermalcoal",
    "ind_tobacco",
    "ind_toolsaccessories",
    "ind_travelservices",
    "ind_trucking",
    "ind_uranium",
    "ind_utilitiesdiversified",
    "ind_utilitiesindependentpowerproducers",
    "ind_utilitiesregulatedelectric",
    "ind_utilitiesregulatedgas",
    "ind_utilitiesregulatedwater",
    "ind_utilitiesrenewable",
    "ind_wastemanagement",
]

VALID_WORKSHEETS = ["all"] + SECTORS + INDUSTRIES

SECTOR_DISPLAY_NAMES = {
    "basicmaterials": "Basic Materials",
    "communicationservices": "Communication Services",
    "consumercyclical": "Consumer Cyclical",
    "consumerdefensive": "Consumer Defensive",
    "energy": "Energy",
    "financial": "Financial",
    "healthcare": "Healthcare",
    "industrials": "Industrials",
    "realestate": "Real Estate",
    "technology": "Technology",
    "utilities": "Utilities",
}

INDUSTRY_DISPLAY_NAMES = {
    "advertisingagencies": "Advertising Agencies",
    "aerospacedefense": "Aerospace & Defense",
    "agriculturalinputs": "Agricultural Inputs",
    "airlines": "Airlines",
    "airportsairservices": "Airports & Air Services",
    "aluminum": "Aluminum",
    "apparelmanufacturing": "Apparel Manufacturing",
    "apparelretail": "Apparel Retail",
    "assetmanagement": "Asset Management",
    "automanufacturers": "Auto Manufacturers",
    "autoparts": "Auto Parts",
    "autotruckdealerships": "Auto & Truck Dealerships",
    "banksdiversified": "Banks - Diversified",
    "banksregional": "Banks - Regional",
    "beveragesbrewers": "Beverages - Brewers",
    "beveragesnonalcoholic": "Beverages - Non-Alcoholic",
    "beverageswineriesdistilleries": "Beverages - Wineries & Distilleries",
    "biotechnology": "Biotechnology",
    "broadcasting": "Broadcasting",
    "buildingmaterials": "Building Materials",
    "buildingproductsequipment": "Building Products & Equipment",
    "businessequipmentsupplies": "Business Equipment & Supplies",
    "capitalmarkets": "Capital Markets",
    "chemicals": "Chemicals",
    "closedendfunddebt": "Closed-End Fund - Debt",
    "closedendfundequity": "Closed-End Fund - Equity",
    "closedendfundforeign": "Closed-End Fund - Foreign",
    "cokingcoal": "Coking Coal",
    "communicationequipment": "Communication Equipment",
    "computerhardware": "Computer Hardware",
    "confectioners": "Confectioners",
    "conglomerates": "Conglomerates",
    "consultingservices": "Consulting Services",
    "consumerelectronics": "Consumer Electronics",
    "copper": "Copper",
    "creditservices": "Credit Services",
    "departmentstores": "Department Stores",
    "diagnosticsresearch": "Diagnostics & Research",
    "discountstores": "Discount Stores",
    "drugmanufacturersgeneral": "Drug Manufacturers - General",
    "drugmanufacturersspecialtygeneric": "Drug Manufacturers - Specialty & Generic",
    "educationtrainingservices": "Education & Training Services",
    "electricalequipmentparts": "Electrical Equipment & Parts",
    "electroniccomponents": "Electronic Components",
    "electronicgamingmultimedia": "Electronic Gaming & Multimedia",
    "electronicscomputerdistribution": "Electronics & Computer Distribution",
    "engineeringconstruction": "Engineering & Construction",
    "entertainment": "Entertainment",
    "exchangetradedfund": "Exchange Traded Fund",
    "farmheavyconstructionmachinery": "Farm & Heavy Construction Machinery",
    "farmproducts": "Farm Products",
    "financialconglomerates": "Financial Conglomerates",
    "financialdatastockexchanges": "Financial Data & Stock Exchanges",
    "fooddistribution": "Food Distribution",
    "footwearaccessories": "Footwear & Accessories",
    "furnishingsfixturesappliances": "Furnishings, Fixtures & Appliances",
    "gambling": "Gambling",
    "gold": "Gold",
    "grocerystores": "Grocery Stores",
    "healthcareplans": "Healthcare Plans",
    "healthinformationservices": "Health Information Services",
    "homeimprovementretail": "Home Improvement Retail",
    "householdpersonalproducts": "Household & Personal Products",
    "industrialdistribution": "Industrial Distribution",
    "informationtechnologyservices": "Information Technology Services",
    "infrastructureoperations": "Infrastructure Operations",
    "insurancebrokers": "Insurance - Brokers",
    "insurancediversified": "Insurance - Diversified",
    "insurancelife": "Insurance - Life",
    "insurancepropertycasualty": "Insurance - Property & Casualty",
    "insurancereinsurance": "Insurance - Reinsurance",
    "insurancespecialty": "Insurance - Specialty",
    "integratedfreightlogistics": "Integrated Freight & Logistics",
    "internetcontentinformation": "Internet Content & Information",
    "internetretail": "Internet Retail",
    "leisure": "Leisure",
    "lodging": "Lodging",
    "lumberwoodproduction": "Lumber & Wood Production",
    "luxurygoods": "Luxury Goods",
    "marineshipping": "Marine Shipping",
    "medicalcarefacilities": "Medical Care Facilities",
    "medicaldevices": "Medical Devices",
    "medicaldistribution": "Medical Distribution",
    "medicalinstrumentssupplies": "Medical Instruments & Supplies",
    "metalfabrication": "Metal Fabrication",
    "mortgagefinance": "Mortgage Finance",
    "oilgasdrilling": "Oil & Gas Drilling",
    "oilgasep": "Oil & Gas E&P",
    "oilgasequipmentservices": "Oil & Gas Equipment & Services",
    "oilgasintegrated": "Oil & Gas Integrated",
    "oilgasmidstream": "Oil & Gas Midstream",
    "oilgasrefiningmarketing": "Oil & Gas Refining & Marketing",
    "otherindustrialmetalsmining": "Other Industrial Metals & Mining",
    "otherpreciousmetalsmining": "Other Precious Metals & Mining",
    "packagedfoods": "Packaged Foods",
    "packagingcontainers": "Packaging & Containers",
    "paperpaperproducts": "Paper & Paper Products",
    "personalservices": "Personal Services",
    "pharmaceuticalretailers": "Pharmaceutical Retailers",
    "pollutiontreatmentcontrols": "Pollution & Treatment Controls",
    "publishing": "Publishing",
    "railroads": "Railroads",
    "realestatedevelopment": "Real Estate - Development",
    "realestatediversified": "Real Estate - Diversified",
    "realestateservices": "Real Estate Services",
    "recreationalvehicles": "Recreational Vehicles",
    "reitdiversified": "REIT - Diversified",
    "reithealthcarefacilities": "REIT - Healthcare Facilities",
    "reithotelmotel": "REIT - Hotel & Motel",
    "reitindustrial": "REIT - Industrial",
    "reitmortgage": "REIT - Mortgage",
    "reitoffice": "REIT - Office",
    "reitresidential": "REIT - Residential",
    "reitretail": "REIT - Retail",
    "reitspecialty": "REIT - Specialty",
    "rentalleasingservices": "Rental & Leasing Services",
    "residentialconstruction": "Residential Construction",
    "resortscasinos": "Resorts & Casinos",
    "restaurants": "Restaurants",
    "scientifictechnicalinstruments": "Scientific & Technical Instruments",
    "securityprotectionservices": "Security & Protection Services",
    "semiconductorequipmentmaterials": "Semiconductor Equipment & Materials",
    "semiconductors": "Semiconductors",
    "shellcompanies": "Shell Companies",
    "silver": "Silver",
    "softwareapplication": "Software - Application",
    "softwareinfrastructure": "Software - Infrastructure",
    "solar": "Solar",
    "specialtybusinessservices": "Specialty Business Services",
    "specialtychemicals": "Specialty Chemicals",
    "specialtyindustrialmachinery": "Specialty Industrial Machinery",
    "specialtyretail": "Specialty Retail",
    "staffingemploymentservices": "Staffing & Employment Services",
    "steel": "Steel",
    "telecomservices": "Telecom Services",
    "textilemanufacturing": "Textile Manufacturing",
    "thermalcoal": "Thermal Coal",
    "tobacco": "Tobacco",
    "toolsaccessories": "Tools & Accessories",
    "travelservices": "Travel Services",
    "trucking": "Trucking",
    "uranium": "Uranium",
    "utilitiesdiversified": "Utilities - Diversified",
    "utilitiesindependentpowerproducers": "Utilities - Independent Power Producers",
    "utilitiesregulatedelectric": "Utilities - Regulated Electric",
    "utilitiesregulatedgas": "Utilities - Regulated Gas",
    "utilitiesregulatedwater": "Utilities - Regulated Water",
    "utilitiesrenewable": "Utilities - Renewable",
    "wastemanagement": "Waste Management",
}

# Sector -> list of industry keys (FINVIZ classification)
SECTOR_INDUSTRIES = {
    "sec_basicmaterials": [
        "ind_agriculturalinputs",
        "ind_aluminum",
        "ind_buildingmaterials",
        "ind_chemicals",
        "ind_cokingcoal",
        "ind_copper",
        "ind_gold",
        "ind_lumberwoodproduction",
        "ind_otherindustrialmetalsmining",
        "ind_otherpreciousmetalsmining",
        "ind_paperpaperproducts",
        "ind_silver",
        "ind_specialtychemicals",
        "ind_steel",
    ],
    "sec_communicationservices": [
        "ind_advertisingagencies",
        "ind_broadcasting",
        "ind_electronicgamingmultimedia",
        "ind_entertainment",
        "ind_internetcontentinformation",
        "ind_publishing",
        "ind_telecomservices",
    ],
    "sec_consumercyclical": [
        "ind_apparelmanufacturing",
        "ind_apparelretail",
        "ind_automanufacturers",
        "ind_autoparts",
        "ind_autotruckdealerships",
        "ind_departmentstores",
        "ind_footwearaccessories",
        "ind_furnishingsfixturesappliances",
        "ind_gambling",
        "ind_homeimprovementretail",
        "ind_internetretail",
        "ind_leisure",
        "ind_lodging",
        "ind_luxurygoods",
        "ind_packagingcontainers",
        "ind_personalservices",
        "ind_recreationalvehicles",
        "ind_residentialconstruction",
        "ind_resortscasinos",
        "ind_restaurants",
        "ind_specialtyretail",
        "ind_textilemanufacturing",
        "ind_travelservices",
    ],
    "sec_consumerdefensive": [
        "ind_beveragesbrewers",
        "ind_beveragesnonalcoholic",
        "ind_beverageswineriesdistilleries",
        "ind_confectioners",
        "ind_discountstores",
        "ind_educationtrainingservices",
        "ind_farmproducts",
        "ind_fooddistribution",
        "ind_grocerystores",
        "ind_householdpersonalproducts",
        "ind_packagedfoods",
        "ind_tobacco",
    ],
    "sec_energy": [
        "ind_oilgasdrilling",
        "ind_oilgasep",
        "ind_oilgasequipmentservices",
        "ind_oilgasintegrated",
        "ind_oilgasmidstream",
        "ind_oilgasrefiningmarketing",
        "ind_thermalcoal",
        "ind_uranium",
    ],
    "sec_financial": [
        "ind_assetmanagement",
        "ind_banksdiversified",
        "ind_banksregional",
        "ind_capitalmarkets",
        "ind_closedendfunddebt",
        "ind_closedendfundequity",
        "ind_closedendfundforeign",
        "ind_creditservices",
        "ind_exchangetradedfund",
        "ind_financialconglomerates",
        "ind_financialdatastockexchanges",
        "ind_insurancebrokers",
        "ind_insurancediversified",
        "ind_insurancelife",
        "ind_insurancepropertycasualty",
        "ind_insurancereinsurance",
        "ind_insurancespecialty",
        "ind_mortgagefinance",
        "ind_shellcompanies",
    ],
    "sec_healthcare": [
        "ind_biotechnology",
        "ind_diagnosticsresearch",
        "ind_drugmanufacturersgeneral",
        "ind_drugmanufacturersspecialtygeneric",
        "ind_healthcareplans",
        "ind_healthinformationservices",
        "ind_medicalcarefacilities",
        "ind_medicaldevices",
        "ind_medicaldistribution",
        "ind_medicalinstrumentssupplies",
        "ind_pharmaceuticalretailers",
    ],
    "sec_industrials": [
        "ind_aerospacedefense",
        "ind_airlines",
        "ind_airportsairservices",
        "ind_buildingproductsequipment",
        "ind_businessequipmentsupplies",
        "ind_conglomerates",
        "ind_consultingservices",
        "ind_electricalequipmentparts",
        "ind_engineeringconstruction",
        "ind_farmheavyconstructionmachinery",
        "ind_industrialdistribution",
        "ind_infrastructureoperations",
        "ind_integratedfreightlogistics",
        "ind_marineshipping",
        "ind_metalfabrication",
        "ind_pollutiontreatmentcontrols",
        "ind_railroads",
        "ind_rentalleasingservices",
        "ind_securityprotectionservices",
        "ind_specialtybusinessservices",
        "ind_specialtyindustrialmachinery",
        "ind_staffingemploymentservices",
        "ind_toolsaccessories",
        "ind_trucking",
        "ind_wastemanagement",
    ],
    "sec_realestate": [
        "ind_realestatedevelopment",
        "ind_realestatediversified",
        "ind_realestateservices",
        "ind_reitdiversified",
        "ind_reithealthcarefacilities",
        "ind_reithotelmotel",
        "ind_reitindustrial",
        "ind_reitmortgage",
        "ind_reitoffice",
        "ind_reitresidential",
        "ind_reitretail",
        "ind_reitspecialty",
    ],
    "sec_technology": [
        "ind_communicationequipment",
        "ind_computerhardware",
        "ind_consumerelectronics",
        "ind_electroniccomponents",
        "ind_electronicscomputerdistribution",
        "ind_informationtechnologyservices",
        "ind_scientifictechnicalinstruments",
        "ind_semiconductorequipmentmaterials",
        "ind_semiconductors",
        "ind_softwareapplication",
        "ind_softwareinfrastructure",
        "ind_solar",
    ],
    "sec_utilities": [
        "ind_utilitiesdiversified",
        "ind_utilitiesindependentpowerproducers",
        "ind_utilitiesregulatedelectric",
        "ind_utilitiesregulatedgas",
        "ind_utilitiesregulatedwater",
        "ind_utilitiesrenewable",
    ],
}

# Reverse lookup: industry key -> sector key
INDUSTRY_TO_SECTOR = {
    ind: sec
    for sec, inds in SECTOR_INDUSTRIES.items()
    for ind in inds
}

# Indicator thresholds
UPPER_THRESHOLD = 0.37
LOWER_THRESHOLD = 0.097
MA_PERIOD = 10
PEAK_DISTANCE = 20
PEAK_PROMINENCE = 0.015

# Chart layout
CHART_HEIGHT_RATIO = 500
CHART_HEIGHT_SUMMARY = 450
CHART_HEIGHT_COMPARISON = 600
CHART_Y_MAX_MIN = 0.6
CHART_Y_MAX_MULTIPLIER = 1.1
MAX_INDUSTRY_COMPARISON = 15
CHART_HEIGHT_HEATMAP = 700

# Date range display
DEFAULT_DISPLAY_YEARS = 2

# Dispersion analysis
DISPERSION_CONVERGED_FALLBACK = 0.066  # ~p25 from historical data
DISPERSION_DIVERGED_FALLBACK = 0.110  # ~p75 from historical data
MEAN_RATIO_LOW = 0.20
MEAN_RATIO_HIGH = 0.35
DISPERSION_VELOCITY_WINDOW = 3
DISPERSION_MIN_HISTORY = 60
DISPERSION_MIN_REGIME_DAYS = 3  # minimum consecutive days to confirm regime change
CHART_HEIGHT_DISPERSION = 600
CHART_HEIGHT_REGIME_TIMELINE = 200


def is_sector(worksheet: str) -> bool:
    """Check if a worksheet key is a sector."""
    return worksheet.startswith("sec_")


def is_industry(worksheet: str) -> bool:
    """Check if a worksheet key is an industry."""
    return worksheet.startswith("ind_")
